create_clock -name sys_clk -period 10.0 [get_ports clk]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN V18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]