create_clock -period 10.000 -name clk [get_ports clk]
set_property PACKAGE_PIN <clk_pin> [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports {a[7..0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[7..0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[7..0]}]