create_clock -name clk -period 10.0 [get_ports clk_i]
set_property PACKAGE_PIN <PIN> [get_ports clk_i]
set_property PACKAGE_PIN <PIN> [get_ports rst_i]
set_property PACKAGE_PIN <PIN> [get_ports uart_rx_i]
set_property PACKAGE_PIN <PIN> [get_ports uart_tx_o]
set_property PACKAGE_PIN <PIN> [get_ports spi_sclk_o]
set_property PACKAGE_PIN <PIN> [get_ports spi_mosi_o]
set_property PACKAGE_PIN <PIN> [get_ports spi_miso_i]
set_property PACKAGE_PIN <PIN> [get_ports spi_csn_o]
set_property PACKAGE_PIN <PIN> [get_ports busy_o]
set_property PACKAGE_PIN <PIN> [get_ports err_o]
set_property PACKAGE_PIN <PIN> [get_ports data_valid_o]